version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    depends_on:
      - mlflow

  mlflow:
    image: mlflow/mlflow:2.20.2
    ports:
      - "5000:5000"
    environment:
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: "mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/mlruns"
