name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data
      run: |
        source venv/bin/activate
        python src/main.py --prepare --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Train and Save model
      run: |
        source venv/bin/activate
        python src/main.py --train --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv
        python src/main.py --save models/best_model.pkl --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Evaluate model
      run: |
        source venv/bin/activate
        python src/main.py --evaluate --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv --save models/best_model.pkl

    - name: Archive model
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: models/best_model.pkl

    - name: Start FastAPI
      run: |
        source venv/bin/activate
        nohup uvicorn app:app --reload --host 0.0.0.0 --port 8000 &

    - name: Start MLflow UI
      run: |
        source venv/bin/activate
        nohup mlflow ui --host 0.0.0.0 --port 5000 &
