name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Prepare data
      run: |
        source venv/bin/activate
        python src/main.py --prepare --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Train model
      run: |
        source venv/bin/activate
        python src/main.py --train --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Save model
      run: |
        source venv/bin/activate
        mkdir -p models  # Create the models directory if it doesn't exist
        python src/main.py --save models/best_model.pkl --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Check model directory and file
      run: |
        if [ -d "models" ]; then
          echo "models directory exists"
        else
          echo "models directory does not exist"
        fi
        if [ -f "models/best_model.pkl" ]; then
          echo "models/best_model.pkl exists"
        else
          echo "models/best_model.pkl does not exist"
        fi

    - name: Evaluate model
      run: |
        source venv/bin/activate
        python src/main.py --evaluate --train_path data/churn-bigml-80.csv --test_path data/churn-bigml-20.csv

    - name: Archive model
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: models/best_model.pkl

    - name: Build Docker image
      run: |
        docker build -t mlops_app .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag mlops_app ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_app:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlops_app:latest

    - name: Start TensorBoard
      run: |
        source venv/bin/activate
        nohup tensorboard --logdir logs/fit --host 0.0.0.0 --port 6006 &
